### ISSUE TITLE
Change background-image 🐞

### ISSUE THREAD

**Issue by suyulin** [openwebf/webf#14]
### What version of kraken are you using

0.12+1

### Steps To Reproduce

change
  ```
  background-image: linear-gradient(134deg, #FFFFFF 0%, #FFFFFF 100%);;

```
to 
```
  background-image: linear-gradient(134deg, #FEC6F0 0%, #AEDEF2 100%);

```

**Code example:** 

**Expected results:** 
 UI : background-image change    background-image: linear-gradient(134deg, #FEC6F0 0%, #AEDEF2 100%);

**Actual results:** 

Nothing has changed

**Comment by suyulin** [comment]
change 
**background: #FFFFFF** to   **background-image: linear-gradient(134deg, #FEC6F0 0%, #AEDEF2 100%)**;
show error
```
======== Exception caught by rendering library =====================================================
The following assertion was thrown during paint():
'package:webf/src/rendering/box_decoration_painter.dart': Failed assertion: line 28 pos 12: '_decoration.gradient != null || _rectForCachedBackgroundPaint == null': is not true.

When the exception was thrown, this was the stack: 
#2      BoxDecorationPainter._getBackgroundPaint (package:webf/src/rendering/box_decoration_painter.dart:28:12)
#3      BoxDecorationPainter._paintBackgroundColor (package:webf/src/rendering/box_decoration_painter.dart:232:31)
#4      BoxDecorationPainter.paint (package:webf/src/rendering/box_decoration_painter.dart:365:7)
#5      RenderBoxDecorationMixin.paintDecoration (package:webf/src/rendering/box_decoration.dart:88:17)
#6      RenderBoxModel._chainPaintDecoration (package:webf/src/rendering/box_model.dart:1201:5)
#7      RenderOpacityMixin.paintOpacity (package:webf/src/rendering/opacity.dart:24:15)
#8      RenderBoxModel._chainPaintOpacity (package:webf/src/rendering/box_model.dart:1197:5)
#9      RenderTransformMixin.paintTransform (package:webf/src/rendering/transform.dart:32:15
```

**Comment by suyulin** [comment]
https://github.com/openwebf/webf/blob/dfdd3fc8f7e2b2cb04f888e098359dc4837de877/webf/lib/src/rendering/box_decoration_painter.dart#L28 delete cache condition problem solve
