### ISSUE TITLE
Build bridge source code but failed

### ISSUE THREAD

**Issue by strengthsong** [openwebf/webf#252]
### Affected version

v0.13.2

### No same issues found.

- [X] Yes, I search all issues but not found.

### Env
1. npm 8.1.0
2. node v16.12.0

### Desc
According to this guide https://openkraken.com/guide/contribute/development
and execute the npm run build:bridge:android, and compile error below:

user@MacBook-Pro-3 webf % npm run build:bridge:android

> build:bridge:android
> node scripts/build_android_so

> build
> NODE_ENV=development rollup --config rollup.config.js && npm run mainToC && npm run testToC

src/index.ts → dist/main.js...
[!] (plugin typescript) Error: @rollup/plugin-typescript TS1005: ',' expected.
node_modules/@types/node/ts4.8/util.d.ts (1485:42)

1485         entries(): IterableIterator<[name: string, value: string]>;
                                              ~

Error: @rollup/plugin-typescript TS1005: ',' expected.
    at error (/Users/user/Documents/work/Binance/Code/webf/webf/bridge/polyfill/node_modules/rollup/dist/shared/rollup.js:198:30)
    at throwPluginError (/Users/user/Documents/work/Binance/Code/webf/webf/bridge/polyfill/node_modules/rollup/dist/shared/rollup.js:21718:12)
    at Object.error (/Users/user/Documents/work/Binance/Code/webf/webf/bridge/polyfill/node_modules/rollup/dist/shared/rollup.js:22672:20)
    at emitDiagnostic (/Users/user/Documents/work/Binance/Code/webf/webf/bridge/polyfill/node_modules/@rollup/plugin-typescript/dist/index.js:415:17)
    at reportDiagnostics (/Users/user/Documents/work/Binance/Code/webf/webf/bridge/polyfill/node_modules/@rollup/plugin-typescript/dist/index.js:423:9)
    at Array.forEach (<anonymous>)
    at emitFilesAndReportErrors (/Users/user/Documents/work/Binance/Code/webf/webf/bridge/polyfill/node_modules/typescript/lib/typescript.js:105350:21)
    at Object.result.afterProgramCreate (/Users/user/Documents/work/Binance/Code/webf/webf/bridge/polyfill/node_modules/typescript/lib/typescript.js:105520:13)
    at Object.afterProgramCreate (/Users/user/Documents/work/Binance/Code/webf/webf/bridge/polyfill/node_modules/@rollup/plugin-typescript/dist/index.js:444:29)
    at synchronizeProgram (/Users/user/Documents/work/Binance/Code/webf/webf/bridge/polyfill/node_modules/typescript/lib/typescript.js:105784:22)

npm notice 
npm notice New major version of npm available! 8.1.0 -> 9.5.0
npm notice Changelog: https://github.com/npm/cli/releases/tag/v9.5.0
npm notice Run npm install -g npm@9.5.0 to update!
npm notice 
/Users/user/Documents/work/Binance/Code/webf/webf/node_modules/async-done/index.js:18
    throw err;
    ^

Error [ERR_UNHANDLED_ERROR]: Unhandled error. ({
  uid: 1,
  name: 'compile-polyfill',
  branch: false,
  error: 1,
  duration: [ 1, 83371542 ],
  time: 1676636843240
})
    at new NodeError (node:internal/errors:371:5)
    at Gulp.emit (node:events:379:17)
    at Gulp.emit (node:domain:475:12)
    at Object.error (/Users/user/Documents/work/Binance/Code/webf/webf/node_modules/undertaker/lib/helpers/createExtensions.js:61:10)
    at handler (/Users/user/Documents/work/Binance/Code/webf/webf/node_modules/now-and-later/lib/mapSeries.js:47:14)
    at f (/Users/user/Documents/work/Binance/Code/webf/webf/node_modules/once/once.js:25:25)
    at f (/Users/user/Documents/work/Binance/Code/webf/webf/node_modules/once/once.js:25:25)
    at tryCatch (/Users/user/Documents/work/Binance/Code/webf/webf/node_modules/async-done/index.js:24:15)
    at done (/Users/user/Documents/work/Binance/Code/webf/webf/node_modules/async-done/index.js:40:12)
    at /Users/user/Documents/work/Binance/Code/webf/webf/scripts/tasks.js:166:12 {
  code: 'ERR_UNHANDLED_ERROR',
  context: {
    uid: 1,
    name: 'compile-polyfill',
    branch: false,
    error: 1,
    duration: [ 1, 83371542 ],
    time: 1676636843240
  }
}
npm notice 
npm notice New major version of npm available! 8.1.0 -> 9.5.0
npm notice Changelog: https://github.com/npm/cli/releases/tag/v9.5.0
npm notice Run npm install -g npm@9.5.0 to update!
npm notice

### Code example

NA

### Expected results

build successfully and come out .so file

### Actual results

user@MacBook-Pro-3 webf % npm run build:bridge:android

> build:bridge:android
> node scripts/build_android_so

> build
> NODE_ENV=development rollup --config rollup.config.js && npm run mainToC && npm run testToC

src/index.ts → dist/main.js...
[!] (plugin typescript) Error: @rollup/plugin-typescript TS1005: ',' expected.
node_modules/@types/node/ts4.8/util.d.ts (1485:42)

1485         entries(): IterableIterator<[name: string, value: string]>;
                                              ~

Error: @rollup/plugin-typescript TS1005: ',' expected.
    at error (/Users/user/Documents/work/Binance/Code/webf/webf/bridge/polyfill/node_modules/rollup/dist/shared/rollup.js:198:30)
    at throwPluginError (/Users/user/Documents/work/Binance/Code/webf/webf/bridge/polyfill/node_modules/rollup/dist/shared/rollup.js:21718:12)
    at Object.error (/Users/user/Documents/work/Binance/Code/webf/webf/bridge/polyfill/node_modules/rollup/dist/shared/rollup.js:22672:20)
    at emitDiagnostic (/Users/user/Documents/work/Binance/Code/webf/webf/bridge/polyfill/node_modules/@rollup/plugin-typescript/dist/index.js:415:17)
    at reportDiagnostics (/Users/user/Documents/work/Binance/Code/webf/webf/bridge/polyfill/node_modules/@rollup/plugin-typescript/dist/index.js:423:9)
    at Array.forEach (<anonymous>)
    at emitFilesAndReportErrors (/Users/user/Documents/work/Binance/Code/webf/webf/bridge/polyfill/node_modules/typescript/lib/typescript.js:105350:21)
    at Object.result.afterProgramCreate (/Users/user/Documents/work/Binance/Code/webf/webf/bridge/polyfill/node_modules/typescript/lib/typescript.js:105520:13)
    at Object.afterProgramCreate (/Users/user/Documents/work/Binance/Code/webf/webf/bridge/polyfill/node_modules/@rollup/plugin-typescript/dist/index.js:444:29)
    at synchronizeProgram (/Users/user/Documents/work/Binance/Code/webf/webf/bridge/polyfill/node_modules/typescript/lib/typescript.js:105784:22)

npm notice 
npm notice New major version of npm available! 8.1.0 -> 9.5.0
npm notice Changelog: https://github.com/npm/cli/releases/tag/v9.5.0
npm notice Run npm install -g npm@9.5.0 to update!
npm notice 
/Users/user/Documents/work/Binance/Code/webf/webf/node_modules/async-done/index.js:18
    throw err;
    ^

Error [ERR_UNHANDLED_ERROR]: Unhandled error. ({
  uid: 1,
  name: 'compile-polyfill',
  branch: false,
  error: 1,
  duration: [ 1, 83371542 ],
  time: 1676636843240
})
    at new NodeError (node:internal/errors:371:5)
    at Gulp.emit (node:events:379:17)
    at Gulp.emit (node:domain:475:12)
    at Object.error (/Users/user/Documents/work/Binance/Code/webf/webf/node_modules/undertaker/lib/helpers/createExtensions.js:61:10)
    at handler (/Users/user/Documents/work/Binance/Code/webf/webf/node_modules/now-and-later/lib/mapSeries.js:47:14)
    at f (/Users/user/Documents/work/Binance/Code/webf/webf/node_modules/once/once.js:25:25)
    at f (/Users/user/Documents/work/Binance/Code/webf/webf/node_modules/once/once.js:25:25)
    at tryCatch (/Users/user/Documents/work/Binance/Code/webf/webf/node_modules/async-done/index.js:24:15)
    at done (/Users/user/Documents/work/Binance/Code/webf/webf/node_modules/async-done/index.js:40:12)
    at /Users/user/Documents/work/Binance/Code/webf/webf/scripts/tasks.js:166:12 {
  code: 'ERR_UNHANDLED_ERROR',
  context: {
    uid: 1,
    name: 'compile-polyfill',
    branch: false,
    error: 1,
    duration: [ 1, 83371542 ],
    time: 1676636843240
  }
}
npm notice 
npm notice New major version of npm available! 8.1.0 -> 9.5.0
npm notice Changelog: https://github.com/npm/cli/releases/tag/v9.5.0
npm notice Run npm install -g npm@9.5.0 to update!
npm notice

**Comment by andycall** [comment]
The @types package breaks, use the package versions from https://github.com/openwebf/webf/blob/main/bridge/polyfill/package.json#L27
