### ISSUE TITLE
npm run build:bridge:ios error

### ISSUE THREAD

**Issue by Tommywangh** [openwebf/webf#262]
### Affected version

0.13.3

### No same issues found.

- [X] Yes, I search all issues but not found.

### Steps to Reproduce

> build:bridge:ios
> node scripts/build_ios_framework

> build
> NODE_ENV=development rollup --config rollup.config.js && npm run mainToC && npm run testToC

src/index.ts → dist/main.js...
Created bundle main.js: 82.74 kB → 15.69 kB (gzip)
created dist/main.js in 951ms

src/test/index.js → dist/test.js...
Created bundle test.js: 254.73 kB → 51.14 kB (gzip)
created dist/test.js in 243ms

> mainToC
> node scripts/js_to_c.js -s ../dist/main.js -o ../dist

> testToC
> node scripts/js_to_c.js -s ../dist/test.js -o ../dist -n TestFramework

-- [DEFAULTS] Enabling ARC support by default. ENABLE_ARC not provided!
-- [DEFAULTS] Hiding symbols visibility by default. ENABLE_VISIBILITY not provided!
-- [DEFAULTS] Using NON-strict compiler checks by default. ENABLE_STRICT_TRY_COMPILE not provided!
-- Configuring iphonesimulator build for platform: SIMULATOR64, architecture(s): x86_64
-- Using SDK: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator16.2.sdk
-- Using C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
-- Using CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
-- Using libtool: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool
-- Using install name tool: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/install_name_tool
-- Autoconf target triple: x86_64-apple-ios
-- Using minimum deployment version: 9.0 (SDK version: 16.2)
-- Merging integrated CMake 3.14+ iOS,tvOS,watchOS,macOS toolchain(s) with this toolchain!
-- CMake version: 3.25.1
-- Using a data_ptr size of: 8
-- Bitcode: Disabled
-- ARC: Enabled
-- Hiding symbols: Enabled

up to date, audited 18 packages in 924ms

1 package is looking for funding
  run `npm fund` for details

found 0 vulnerabilities

> code_generator@1.0.0 build
> tsc

fatal: not a git repository (or any of the parent directories): .git
CMake Error at CMakeLists.txt:494 (string):
  string sub-command REPLACE requires at least four arguments.

-- Configuring incomplete, errors occurred!
See also "/Users/aaa/Downloads/webf-0.13.3/bridge/cmake-build-ios-simulator-x86/CMakeFiles/CMakeOutput.log".
See also "/Users/aaa/Downloads/webf-0.13.3/bridge/cmake-build-ios-simulator-x86/CMakeFiles/CMakeError.log".
/Users/aaa/Downloads/webf-0.13.3/node_modules/async-done/index.js:18
    throw err;
    ^

Error [ERR_UNHANDLED_ERROR]: Unhandled error. ({
  uid: 2,
  name: 'build-ios-webf-lib',
  branch: false,
  error: Error: Command failed: cmake -DCMAKE_BUILD_TYPE=Debug     -DCMAKE_TOOLCHAIN_FILE=/Users/aaa/Downloads/webf-0.13.3/bridge/cmake/ios.toolchain.cmake     -DPLATFORM=SIMULATOR64     -DDEPLOYMENT_TARGET=9.0     -DIS_IOS=TRUE     \
           -DENABLE_BITCODE=FALSE -G "Unix Makefiles" -B /Users/aaa/Downloads/webf-0.13.3/bridge/cmake-build-ios-simulator-x86 -S /Users/aaa/Downloads/webf-0.13.3/bridge
      at checkExecSyncError (node:child_process:885:11)
      at execSync (node:child_process:957:15)
      at /Users/aaa/Downloads/webf-0.13.3/scripts/tasks.js:348:3
      at taskWrapper (/Users/aaa/Downloads/webf-0.13.3/node_modules/undertaker/lib/set-task.js:13:15)
      at bound (node:domain:433:15)
      at runBound (node:domain:444:12)
      at asyncRunner (/Users/aaa/Downloads/webf-0.13.3/node_modules/async-done/index.js:55:18)
      at process.processTicksAndRejections (node:internal/process/task_queues:77:11) {
    status: 1,
    signal: null,
    output: [ null, null, null ],
    pid: 56217,
    stdout: null,
    stderr: null,
    domainThrown: true
  },
  duration: [ 4, 35388625 ],
  time: 1677574274541
})
    at new NodeError (node:internal/errors:400:5)
    at Gulp.emit (node:events:502:17)
    at Gulp.emit (node:domain:489:12)
    at Object.error (/Users/aaa/Downloads/webf-0.13.3/node_modules/undertaker/lib/helpers/createExtensions.js:61:10)
    at handler (/Users/aaa/Downloads/webf-0.13.3/node_modules/now-and-later/lib/mapSeries.js:47:14)
    at f (/Users/aaa/Downloads/webf-0.13.3/node_modules/once/once.js:25:25)
    at f (/Users/aaa/Downloads/webf-0.13.3/node_modules/once/once.js:25:25)
    at tryCatch (/Users/aaa/Downloads/webf-0.13.3/node_modules/async-done/index.js:24:15)
    at done (/Users/aaa/Downloads/webf-0.13.3/node_modules/async-done/index.js:40:12)
    at Domain.onError (/Users/aaa/Downloads/webf-0.13.3/node_modules/async-done/index.js:51:5) {
  code: 'ERR_UNHANDLED_ERROR',
  context: {
    uid: 2,
    name: 'build-ios-webf-lib',
    branch: false,
    error: Error: Command failed: cmake -DCMAKE_BUILD_TYPE=Debug     -DCMAKE_TOOLCHAIN_FILE=/Users/aaa/Downloads/webf-0.13.3/bridge/cmake/ios.toolchain.cmake     -DPLATFORM=SIMULATOR64     -DDEPLOYMENT_TARGET=9.0     -DIS_IOS=TRUE     \
             -DENABLE_BITCODE=FALSE -G "Unix Makefiles" -B /Users/aaa/Downloads/webf-0.13.3/bridge/cmake-build-ios-simulator-x86 -S /Users/aaa/Downloads/webf-0.13.3/bridge
        at checkExecSyncError (node:child_process:885:11)
        at execSync (node:child_process:957:15)
        at /Users/aaa/Downloads/webf-0.13.3/scripts/tasks.js:348:3
        at taskWrapper (/Users/aaa/Downloads/webf-0.13.3/node_modules/undertaker/lib/set-task.js:13:15)
        at bound (node:domain:433:15)
        at runBound (node:domain:444:12)
        at asyncRunner (/Users/aaa/Downloads/webf-0.13.3/node_modules/async-done/index.js:55:18)
        at process.processTicksAndRejections (node:internal/process/task_queues:77:11) {
      status: 1,
      signal: null,
      output: [ null, null, null ],
      pid: 56217,
      stdout: null,
      stderr: null,
      domainThrown: true
    },
    duration: [ 4, 35388625 ],
    time: 1677574274541
  }
}

Node.js v19.3.0

> build:bridge:ios
> node scripts/build_ios_framework

> build
> NODE_ENV=development rollup --config rollup.config.js && npm run mainToC && npm run testToC

src/index.ts → dist/main.js...
Created bundle main.js: 82.74 kB → 15.69 kB (gzip)
created dist/main.js in 951ms

src/test/index.js → dist/test.js...
Created bundle test.js: 254.73 kB → 51.14 kB (gzip)
created dist/test.js in 243ms

> mainToC
> node scripts/js_to_c.js -s ../dist/main.js -o ../dist

> testToC
> node scripts/js_to_c.js -s ../dist/test.js -o ../dist -n TestFramework

-- [DEFAULTS] Enabling ARC support by default. ENABLE_ARC not provided!
-- [DEFAULTS] Hiding symbols visibility by default. ENABLE_VISIBILITY not provided!
-- [DEFAULTS] Using NON-strict compiler checks by default. ENABLE_STRICT_TRY_COMPILE not provided!
-- Configuring iphonesimulator build for platform: SIMULATOR64, architecture(s): x86_64
-- Using SDK: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator16.2.sdk
-- Using C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
-- Using CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
-- Using libtool: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool
-- Using install name tool: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/install_name_tool
-- Autoconf target triple: x86_64-apple-ios
-- Using minimum deployment version: 9.0 (SDK version: 16.2)
-- Merging integrated CMake 3.14+ iOS,tvOS,watchOS,macOS toolchain(s) with this toolchain!
-- CMake version: 3.25.1
-- Using a data_ptr size of: 8
-- Bitcode: Disabled
-- ARC: Enabled
-- Hiding symbols: Enabled

up to date, audited 18 packages in 924ms

1 package is looking for funding
  run `npm fund` for details

found 0 vulnerabilities

> code_generator@1.0.0 build
> tsc

fatal: not a git repository (or any of the parent directories): .git
CMake Error at CMakeLists.txt:494 (string):
  string sub-command REPLACE requires at least four arguments.

-- Configuring incomplete, errors occurred!
See also "/Users/aaa/Downloads/webf-0.13.3/bridge/cmake-build-ios-simulator-x86/CMakeFiles/CMakeOutput.log".
See also "/Users/aaa/Downloads/webf-0.13.3/bridge/cmake-build-ios-simulator-x86/CMakeFiles/CMakeError.log".
/Users/aaa/Downloads/webf-0.13.3/node_modules/async-done/index.js:18
    throw err;
    ^

Error [ERR_UNHANDLED_ERROR]: Unhandled error. ({
  uid: 2,
  name: 'build-ios-webf-lib',
  branch: false,
  error: Error: Command failed: cmake -DCMAKE_BUILD_TYPE=Debug     -DCMAKE_TOOLCHAIN_FILE=/Users/aaa/Downloads/webf-0.13.3/bridge/cmake/ios.toolchain.cmake     -DPLATFORM=SIMULATOR64     -DDEPLOYMENT_TARGET=9.0     -DIS_IOS=TRUE     \
           -DENABLE_BITCODE=FALSE -G "Unix Makefiles" -B /Users/aaa/Downloads/webf-0.13.3/bridge/cmake-build-ios-simulator-x86 -S /Users/aaa/Downloads/webf-0.13.3/bridge
      at checkExecSyncError (node:child_process:885:11)
      at execSync (node:child_process:957:15)
      at /Users/aaa/Downloads/webf-0.13.3/scripts/tasks.js:348:3
      at taskWrapper (/Users/aaa/Downloads/webf-0.13.3/node_modules/undertaker/lib/set-task.js:13:15)
      at bound (node:domain:433:15)
      at runBound (node:domain:444:12)
      at asyncRunner (/Users/aaa/Downloads/webf-0.13.3/node_modules/async-done/index.js:55:18)
      at process.processTicksAndRejections (node:internal/process/task_queues:77:11) {
    status: 1,
    signal: null,
    output: [ null, null, null ],
    pid: 56217,
    stdout: null,
    stderr: null,
    domainThrown: true
  },
  duration: [ 4, 35388625 ],
  time: 1677574274541
})
    at new NodeError (node:internal/errors:400:5)
    at Gulp.emit (node:events:502:17)
    at Gulp.emit (node:domain:489:12)
    at Object.error (/Users/aaa/Downloads/webf-0.13.3/node_modules/undertaker/lib/helpers/createExtensions.js:61:10)
    at handler (/Users/aaa/Downloads/webf-0.13.3/node_modules/now-and-later/lib/mapSeries.js:47:14)
    at f (/Users/aaa/Downloads/webf-0.13.3/node_modules/once/once.js:25:25)
    at f (/Users/aaa/Downloads/webf-0.13.3/node_modules/once/once.js:25:25)
    at tryCatch (/Users/aaa/Downloads/webf-0.13.3/node_modules/async-done/index.js:24:15)
    at done (/Users/aaa/Downloads/webf-0.13.3/node_modules/async-done/index.js:40:12)
    at Domain.onError (/Users/aaa/Downloads/webf-0.13.3/node_modules/async-done/index.js:51:5) {
  code: 'ERR_UNHANDLED_ERROR',
  context: {
    uid: 2,
    name: 'build-ios-webf-lib',
    branch: false,
    error: Error: Command failed: cmake -DCMAKE_BUILD_TYPE=Debug     -DCMAKE_TOOLCHAIN_FILE=/Users/aaa/Downloads/webf-0.13.3/bridge/cmake/ios.toolchain.cmake     -DPLATFORM=SIMULATOR64     -DDEPLOYMENT_TARGET=9.0     -DIS_IOS=TRUE     \
             -DENABLE_BITCODE=FALSE -G "Unix Makefiles" -B /Users/aaa/Downloads/webf-0.13.3/bridge/cmake-build-ios-simulator-x86 -S /Users/aaa/Downloads/webf-0.13.3/bridge
        at checkExecSyncError (node:child_process:885:11)
        at execSync (node:child_process:957:15)
        at /Users/aaa/Downloads/webf-0.13.3/scripts/tasks.js:348:3
        at taskWrapper (/Users/aaa/Downloads/webf-0.13.3/node_modules/undertaker/lib/set-task.js:13:15)
        at bound (node:domain:433:15)
        at runBound (node:domain:444:12)
        at asyncRunner (/Users/aaa/Downloads/webf-0.13.3/node_modules/async-done/index.js:55:18)
        at process.processTicksAndRejections (node:internal/process/task_queues:77:11) {
      status: 1,
      signal: null,
      output: [ null, null, null ],
      pid: 56217,
      stdout: null,
      stderr: null,
      domainThrown: true
    },
    duration: [ 4, 35388625 ],
    time: 1677574274541
  }
}

Node.js v19.3.0

> build:bridge:ios
> node scripts/build_ios_framework

> build
> NODE_ENV=development rollup --config rollup.config.js && npm run mainToC && npm run testToC

src/index.ts → dist/main.js...
Created bundle main.js: 82.74 kB → 15.69 kB (gzip)
created dist/main.js in 951ms

src/test/index.js → dist/test.js...
Created bundle test.js: 254.73 kB → 51.14 kB (gzip)
created dist/test.js in 243ms

> mainToC
> node scripts/js_to_c.js -s ../dist/main.js -o ../dist

> testToC
> node scripts/js_to_c.js -s ../dist/test.js -o ../dist -n TestFramework

-- [DEFAULTS] Enabling ARC support by default. ENABLE_ARC not provided!
-- [DEFAULTS] Hiding symbols visibility by default. ENABLE_VISIBILITY not provided!
-- [DEFAULTS] Using NON-strict compiler checks by default. ENABLE_STRICT_TRY_COMPILE not provided!
-- Configuring iphonesimulator build for platform: SIMULATOR64, architecture(s): x86_64
-- Using SDK: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator16.2.sdk
-- Using C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
-- Using CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
-- Using libtool: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool
-- Using install name tool: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/install_name_tool
-- Autoconf target triple: x86_64-apple-ios
-- Using minimum deployment version: 9.0 (SDK version: 16.2)
-- Merging integrated CMake 3.14+ iOS,tvOS,watchOS,macOS toolchain(s) with this toolchain!
-- CMake version: 3.25.1
-- Using a data_ptr size of: 8
-- Bitcode: Disabled
-- ARC: Enabled
-- Hiding symbols: Enabled

up to date, audited 18 packages in 924ms

1 package is looking for funding
  run `npm fund` for details

found 0 vulnerabilities

> code_generator@1.0.0 build
> tsc

fatal: not a git repository (or any of the parent directories): .git
CMake Error at CMakeLists.txt:494 (string):
  string sub-command REPLACE requires at least four arguments.

-- Configuring incomplete, errors occurred!
See also "/Users/aaa/Downloads/webf-0.13.3/bridge/cmake-build-ios-simulator-x86/CMakeFiles/CMakeOutput.log".
See also "/Users/aaa/Downloads/webf-0.13.3/bridge/cmake-build-ios-simulator-x86/CMakeFiles/CMakeError.log".
/Users/aaa/Downloads/webf-0.13.3/node_modules/async-done/index.js:18
    throw err;
    ^

Error [ERR_UNHANDLED_ERROR]: Unhandled error. ({
  uid: 2,
  name: 'build-ios-webf-lib',
  branch: false,
  error: Error: Command failed: cmake -DCMAKE_BUILD_TYPE=Debug     -DCMAKE_TOOLCHAIN_FILE=/Users/aaa/Downloads/webf-0.13.3/bridge/cmake/ios.toolchain.cmake     -DPLATFORM=SIMULATOR64     -DDEPLOYMENT_TARGET=9.0     -DIS_IOS=TRUE     \
           -DENABLE_BITCODE=FALSE -G "Unix Makefiles" -B /Users/aaa/Downloads/webf-0.13.3/bridge/cmake-build-ios-simulator-x86 -S /Users/aaa/Downloads/webf-0.13.3/bridge
      at checkExecSyncError (node:child_process:885:11)
      at execSync (node:child_process:957:15)
      at /Users/aaa/Downloads/webf-0.13.3/scripts/tasks.js:348:3
      at taskWrapper (/Users/aaa/Downloads/webf-0.13.3/node_modules/undertaker/lib/set-task.js:13:15)
      at bound (node:domain:433:15)
      at runBound (node:domain:444:12)
      at asyncRunner (/Users/aaa/Downloads/webf-0.13.3/node_modules/async-done/index.js:55:18)
      at process.processTicksAndRejections (node:internal/process/task_queues:77:11) {
    status: 1,
    signal: null,
    output: [ null, null, null ],
    pid: 56217,
    stdout: null,
    stderr: null,
    domainThrown: true
  },
  duration: [ 4, 35388625 ],
  time: 1677574274541
})
    at new NodeError (node:internal/errors:400:5)
    at Gulp.emit (node:events:502:17)
    at Gulp.emit (node:domain:489:12)
    at Object.error (/Users/aaa/Downloads/webf-0.13.3/node_modules/undertaker/lib/helpers/createExtensions.js:61:10)
    at handler (/Users/aaa/Downloads/webf-0.13.3/node_modules/now-and-later/lib/mapSeries.js:47:14)
    at f (/Users/aaa/Downloads/webf-0.13.3/node_modules/once/once.js:25:25)
    at f (/Users/aaa/Downloads/webf-0.13.3/node_modules/once/once.js:25:25)
    at tryCatch (/Users/aaa/Downloads/webf-0.13.3/node_modules/async-done/index.js:24:15)
    at done (/Users/aaa/Downloads/webf-0.13.3/node_modules/async-done/index.js:40:12)
    at Domain.onError (/Users/aaa/Downloads/webf-0.13.3/node_modules/async-done/index.js:51:5) {
  code: 'ERR_UNHANDLED_ERROR',
  context: {
    uid: 2,
    name: 'build-ios-webf-lib',
    branch: false,
    error: Error: Command failed: cmake -DCMAKE_BUILD_TYPE=Debug     -DCMAKE_TOOLCHAIN_FILE=/Users/aaa/Downloads/webf-0.13.3/bridge/cmake/ios.toolchain.cmake     -DPLATFORM=SIMULATOR64     -DDEPLOYMENT_TARGET=9.0     -DIS_IOS=TRUE     \
             -DENABLE_BITCODE=FALSE -G "Unix Makefiles" -B /Users/aaa/Downloads/webf-0.13.3/bridge/cmake-build-ios-simulator-x86 -S /Users/aaa/Downloads/webf-0.13.3/bridge
        at checkExecSyncError (node:child_process:885:11)
        at execSync (node:child_process:957:15)
        at /Users/aaa/Downloads/webf-0.13.3/scripts/tasks.js:348:3
        at taskWrapper (/Users/aaa/Downloads/webf-0.13.3/node_modules/undertaker/lib/set-task.js:13:15)
        at bound (node:domain:433:15)
        at runBound (node:domain:444:12)
        at asyncRunner (/Users/aaa/Downloads/webf-0.13.3/node_modules/async-done/index.js:55:18)
        at process.processTicksAndRejections (node:internal/process/task_queues:77:11) {
      status: 1,
      signal: null,
      output: [ null, null, null ],
      pid: 56217,
      stdout: null,
      stderr: null,
      domainThrown: true
    },
    duration: [ 4, 35388625 ],
    time: 1677574274541
  }
}

Node.js v19.3.0

### Code example

1

### Expected results

build success

### Actual results

build failed

**Comment by andycall** [comment]
Only works on git projects 
```
fatal: not a git repository (or any of the parent directories): .git
CMake Error at CMakeLists.txt:494 (string):
string sub-command REPLACE requires at least four arguments.
```
