### ISSUE TITLE
Can not run bridge build

### ISSUE THREAD

**Issue by looseyi** [openwebf/webf#357]
### Affected version

beta/0.14.0

### No same issues found.

- [X] Yes, I search all issues but not found.

### Steps to Reproduce

npm run build:bridge:ios

### Code example

npm run build:bridge:ios

### Expected results

> build:bridge:ios
> node scripts/build_ios_framework

> build
> cross-env NODE_ENV=development rollup --config rollup.config.js && npm run mainToC && npm run testToC

src/index.ts → dist/main.js...
[!] (plugin typescript) Error: @rollup/plugin-typescript TS2345: Argument of type '{ get(target: Storage, p: string | symbol, receiver: any): any; set(target: Storage, p: string | symbol, newValue: any, receiver: any): boolean; has(target: Storage, p: string | symbol): boolean; ownKeys(target: Storage): ArrayLike<...>; deleteProperty(target: Storage, p: string | symbol): boolean; defineProperty(ta...' is not assignable to parameter of type 'ProxyHandler<Storage>'.
  The types returned by 'ownKeys(...)' are incompatible between these types.
    Type 'ArrayLike<string | symbol>' is missing the following properties from type '(string | number | symbol)[]': pop, push, concat, join, and 28 more.
src/local-storage.ts (7:68)

7 export const localStorage = new Proxy(new Storage('LocalStorage'), storageProxyHandler);
                                                                     ~~~~~~~~~~~~~~~~~~~

Error: @rollup/plugin-typescript TS2345: Argument of type '{ get(target: Storage, p: string | symbol, receiver: any): any; set(target: Storage, p: string | symbol, newValue: any, receiver: any): boolean; has(target: Storage, p: string | symbol): boolean; ownKeys(target: Storage): ArrayLike<...>; deleteProperty(target: Storage, p: string | symbol): boolean; defineProperty(ta...' is not assignable to parameter of type 'ProxyHandler<Storage>'.
  The types returned by 'ownKeys(...)' are incompatible between these types.
    Type 'ArrayLike<string | symbol>' is missing the following properties from type '(string | number | symbol)[]': pop, push, concat, join, and 28 more.
    at error (/Users/user/Desktop/Binance/webf/bridge/polyfill/node_modules/rollup/dist/shared/rollup.js:198:30)
    at throwPluginError (/Users/user/Desktop/Binance/webf/bridge/polyfill/node_modules/rollup/dist/shared/rollup.js:21919:12)
    at Object.error (/Users/user/Desktop/Binance/webf/bridge/polyfill/node_modules/rollup/dist/shared/rollup.js:22641:20)
    at emitDiagnostic (/Users/user/Desktop/Binance/webf/bridge/polyfill/node_modules/@rollup/plugin-typescript/dist/index.js:415:17)
    at reportDiagnostics (/Users/user/Desktop/Binance/webf/bridge/polyfill/node_modules/@rollup/plugin-typescript/dist/index.js:423:9)
    at Array.forEach (<anonymous>)
    at emitFilesAndReportErrors (/Users/user/Desktop/Binance/webf/bridge/polyfill/node_modules/typescript/lib/typescript.js:105350:21)
    at Object.result.afterProgramCreate (/Users/user/Desktop/Binance/webf/bridge/polyfill/node_modules/typescript/lib/typescript.js:105520:13)
    at Object.afterProgramCreate (/Users/user/Desktop/Binance/webf/bridge/polyfill/node_modules/@rollup/plugin-typescript/dist/index.js:444:29)
    at synchronizeProgram (/Users/user/Desktop/Binance/webf/bridge/polyfill/node_modules/typescript/lib/typescript.js:105784:22)

/Users/user/Desktop/Binance/webf/node_modules/async-done/index.js:18
    throw err;
    ^

Error [ERR_UNHANDLED_ERROR]: Unhandled error. ({
  uid: 1,
  name: 'compile-polyfill',
  branch: false,
  error: 1,
  duration: [ 1, 162214584 ],
  time: 1684895279527
})
    at new NodeError (node:internal/errors:371:5)
    at Gulp.emit (node:events:379:17)
    at Gulp.emit (node:domain:475:12)
    at Object.error (/Users/user/Desktop/Binance/webf/node_modules/undertaker/lib/helpers/createExtensions.js:61:10)
    at handler (/Users/user/Desktop/Binance/webf/node_modules/now-and-later/lib/mapSeries.js:47:14)
    at f (/Users/user/Desktop/Binance/webf/node_modules/once/once.js:25:25)
    at f (/Users/user/Desktop/Binance/webf/node_modules/once/once.js:25:25)
    at tryCatch (/Users/user/Desktop/Binance/webf/node_modules/async-done/index.js:24:15)
    at done (/Users/user/Desktop/Binance/webf/node_modules/async-done/index.js:40:12)
    at /Users/user/Desktop/Binance/webf/scripts/tasks.js:168:12 {
  code: 'ERR_UNHANDLED_ERROR',
  context: {
    uid: 1,
    name: 'compile-polyfill',
    branch: false,
    error: 1,
    duration: [ 1, 162214584 ],
    time: 1684895279527
  }
}

### Actual results

it just work on the last merge-remote from origin/main

**Comment by andycall** [comment]
run `git clean -xfd .`  and retry

**Comment by looseyi** [comment]
> run `git clean -xfd .` and retry

it works, thanks for the feedback

**Comment by looseyi** [comment]
<img width="795" alt="image" src="https://github.com/openwebf/webf/assets/5006424/3124f7c3-c6bc-451d-a9cb-1cae50114f5d">
here is another problem, after install

**Comment by looseyi** [comment]
Error: Couldn't resolve the package 'archive' in 'package:archive/archive.dart'.

**Comment by looseyi** [comment]
fix by flutter pub get. 
thanks
