### ISSUE TITLE
webf_unit_test.exe does not get built

### ISSUE THREAD

**Issue by calvinchengx** [openwebf/webf#363]
### Affected version

main

### No same issues found.

- [X] Yes, I search all issues but not found.

### Steps to Reproduce

`scripts/tasks.js` is updated in L580 to build a `webf_unit_test.exe` binary, so that I can run unit tests locally on my windows machine.

### Code example

  ```js
const webfTargets = ['webf'];
webfTargets.push('webf_unit_test');
```

### Expected results

`C:\openwebf\webf\bridge\build\windows\lib\webf_unit_test.exe`

Gets built correctly.

So that developer can run this locally.

### Actual results

```log
MSBuild version 17.6.3+07e294721 for .NET Framework
MSBUILD : error MSB1009: Project file does not exist.
Switch: webf_unit_test.vcxproj
C:\openwebf\webf\node_modules\async-done\index.js:18
    throw err;
    ^

Error [ERR_UNHANDLED_ERROR]: Unhandled error. ({
  uid: 3,
  name: 'build-window-webf-lib',
  branch: false,
  error: Error: Command failed: cmake --build C:\openwebf\webf\bridge\cmake-build-windows --target webf webf_unit_test --verbose --config Debug
      at checkExecSyncError (node:child_process:826:11)
      at execSync (node:child_process:900:15)
      at C:\openwebf\webf\scripts\tasks.js:584:3
      at taskWrapper (C:\openwebf\webf\node_modules\undertaker\lib\set-task.js:13:15)
      at bound (node:domain:416:15)
      at runBound (node:domain:427:12)
      at asyncRunner (C:\openwebf\webf\node_modules\async-done\index.js:55:18)
      at processTicksAndRejections (node:internal/process/task_queues:78:11) {
    status: 1,
    signal: null,
    output: [ null, null, null ],
    pid: 29668,
    stdout: null,
    stderr: null,
    domainThrown: true
  },
  duration: [ 37, 851988600 ],
  time: 1685020909630
})
```

**Comment by andycall** [comment]
Unit test executable only supported in macOS
