### ISSUE TITLE
 ReferenceError: 'MutationObserver' is not defined

### ISSUE THREAD

**Issue by helixs** [openwebf/webf#405]
### Affected version

0.14.0

### No same issues found.

- [X] Yes, I search all issues but not found.

### Steps to Reproduce

使用Vue最新版本的Cli，创建新项目，会有[MutationObserver](https://developer.mozilla.org/zh-CN/docs/Web/API/MutationObserver)

### Code example

```dart
class MyApp extends StatefulWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  State<MyApp> createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  @override
  Widget build(BuildContext context) {
    final MediaQueryData queryData = MediaQuery.of(context);
    final Size viewportSize = queryData.size;
    return Scaffold(
        appBar: AppBar(
          // Here we take the value from the MyHomePage object that was created by
          // the App.build method, and use it to set our appbar title.
          title: Text("xixi"),
        ),
        body: Center(
          child: Column(
            children: [
              WebF(
                devToolsService: ChromeDevToolsService(), // Enable Chrome DevTools Services
                viewportWidth: viewportSize.width - queryData.padding.horizontal, // Adjust the viewportWidth
                viewportHeight: viewportSize.height - queryData.padding.vertical, // Adjust the viewportHeight
                bundle: WebFBundle.fromUrl('http://172.16.25.118:8000/'), // The page entry point
              ),
            ],
          ),
        ));
  }
}

```

### Expected results

正常显示

### Actual results

E/WEBF_NATIVE_LOG( 6868): ReferenceError: 'MutationObserver' is not defined
E/WEBF_NATIVE_LOG( 6868):     at <anonymous> (http://172.16.25.142:8000/assets/index-393e57c5.js:1:192)
E/WEBF_NATIVE_LOG( 6868):     at <eval> (http://172.16.25.142:8000/assets/index-393e57c5.js:1:1)
E/WEBF_NATIVE_LOG( 6868): 
I/flutter ( 6868): Script code are not valid to evaluate.
I/flutter ( 6868): #0      ScriptRunner._evaluateScriptBundle (package:webf/src/html/script.dart:47:9)
I/flutter ( 6868): <asynchronous suspension>
I/flutter ( 6868): #1      ScriptRunner._queueScriptForExecution.task (package:webf/src/html/script.dart:93:9)
I/flutter ( 6868): <asynchronous suspension>
I/flutter ( 6868): #2      ScriptRunner._execute (package:webf/src/html/script.dart:64:7)
I/flutter ( 6868): <asynchronous suspension>
I/flutter ( 6868):

**Comment by helixs** [comment]
添加了，这个问题也解决了。不过又出现了以下错误，我不是前端开发人员，所以不好排查。我直接写一个简单的html是没啥问题的，用框架编译就有这些问题。哈哈哈，尴尬。
```
E/WEBF_NATIVE_LOG(23997): SyntaxError: invalid number literal
E/WEBF_NATIVE_LOG(23997):     at http://172.16.25.142:8000/assets/index-89e532dd.js:2:2976
E/WEBF_NATIVE_LOG(23997): 
I/flutter (23997): Invalid argument(s): length must be in the range [0, 1073741823].
I/flutter (23997): #0      _checkExternalTypedDataLength (dart:ffi-patch/ffi_patch.dart:60:5)
I/flutter (23997): #1      Uint8Pointer.asTypedList (dart:ffi-patch/ffi_patch.dart:620:5)
I/flutter (23997): #2      evaluateScripts (package:webf/src/bridge/to_native.dart:165:43)
I/flutter (23997): <asynchronous suspension>
I/flutter (23997): #3      ScriptRunner._evaluateScriptBundle (package:webf/src/html/script.dart:45:21)
I/flutter (23997): <asynchronous suspension>
I/flutter (23997): #4      ScriptRunner._queueScriptForExecution.task (package:webf/src/html/script.dart:93:9)
I/flutter (23997): <asynchronous suspension>
I/flutter (23997): #5      ScriptRunner._execute (package:webf/src/html/script.dart:64:7)
I/flutter (23997): <asynchronous suspension>
I/flutter (23997): Script code are not valid to evaluate.
I/flutter (23997): #0      ScriptRunner._evaluateScriptBundle (package:webf/src/html/script.dart:47:9)
I/flutter (23997): <asynchronous suspension>
I/flutter (23997): #1      ScriptRunner._queueScriptForExecution.task (package:webf/src/html/script.dart:93:9)
I/flutter (23997): <asynchronous suspension>
I/flutter (23997): #2      ScriptRunner._execute (package:webf/src/html/script.dart:64:7)
I/flutter (23997): <asynchronous suspension>
I/flutter (23997): 
```

**Comment by XGHeaven** [comment]
看起来是用了一些不认识的语法？他不是打印出行号了么，你定位过去看一下

**Comment by helixs** [comment]
找到了
`0xde0b6b3a7640080.toFixed(0)!=="1000000000000000128"`
