### ISSUE TITLE
软件崩溃 unsupported keyword: export

### ISSUE THREAD

**Issue by ShylockGao** [openwebf/webf#583]
### Affected version

0.16.0-beta.5

### Flutter versions

3.16.5

### No same issues found.

- [X] Yes, I search all issues but not found.

### Steps to Reproduce

1、教程初始化访问
提示 
SyntaxError: unsupported keyword: export
    at https://tronplayai.com/assets/index.6b999624.js:5:101133

### Code example

```dart
  @override
  Widget build(BuildContext context) {
    final MediaQueryData queryData = MediaQuery.of(context);
    final Size viewportSize = queryData.size;

    return Scaffold(
      body: Column(
        children: [
          // ElevatedButton(onPressed: (){}, child: Text("xxxxxxxxxxxxxx")),

          WebF(
            devToolsService: ChromeDevToolsService(), // Enable Chrome DevTools Services
            viewportWidth: viewportSize.width - queryData.padding.horizontal, // Adjust the viewportWidth
            viewportHeight: viewportSize.height - queryData.padding.vertical, // Adjust the viewportHeight
            bundle: WebFBundle.fromUrl('https://tronplayai.com/'), // The page entry point
          ),
        ],
      )
    );
  }
```

### Expected results

正常页面展示

### Actual results

app崩溃
提示 
SyntaxError: unsupported keyword: export
    at https://tronplayai.com/assets/index.6b999624.js:5:101133

**Comment by muzipiao** [comment]
这个库问题很多，缩放窗口也会Crash

**Comment by aymonYU** [comment]
遇到相同的问题，vue3代码编译dist的js 都是有export关键字，貌似是quickjs 不支持 js export模块

**Comment by andycall** [comment]
不支持esm module，需要用vue-cli 构建

**Comment by andycall** [comment]
> 这个库问题很多，缩放窗口也会Crash

有issue 吗？

**Comment by andycall** [comment]
duplicated with https://github.com/openwebf/webf/issues/124
