### ISSUE TITLE
How to build libwebf.so for arm64 of linux

### ISSUE THREAD

**Issue by fisherjoe** [openwebf/webf#705]
### Feature type

Others

### The spec link.

https://www.yingzi.com

### How much important for you

We have a ubuntu run on  nvidia arm64 platform，but webf have no such arc library!

**Comment by andycall** [comment]
Clone the source code and compile by yourself. I tested on my Ubuntu Arm64 running in paralle desktop.

```
npm run build:bridge:linux:release
```

**Comment by fisherjoe** [comment]
> Clone the source code and compile by yourself. I tested on my Ubuntu Arm64 running in paralle desktop.
> 
> ```
> npm run build:bridge:linux:release
> ```

Yes! I have build as your introdution. 
But when I run the demo, There is error as follow:

[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Null check operator used on a null value
#0      WebFController.preload (package:webf/src/launcher/controller.dart:1308:34)
<asynchronous suspension>

The Flutter DevTools debugger and profiler on Linux is available at:
http://127.0.0.1:9100?uri=http://127.0.0.1:39033/4wZSSvDM9KA=/
flutter: WebF DevTool listening at ws://172.16.60.197:9222
flutter: Open Chrome/Edge and enter following url to your navigator:
flutter:     devtools://devtools/bundled/inspector.html?ws=172.16.60.197:9222
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: 'package:webf/src/dom/document.dart': Failed assertion: line 420 pos 12: 'documentElement != null': is not true.
#0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:50:61)
#1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:40:5)
#2      Document.initializeRootElementSize (package:webf/src/dom/document.dart:420:12)
#3      _WebFRenderObjectElement.mount.<anonymous closure> (package:webf/src/widget/webf.dart:473:35)
#4      SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1397:15)
#5      SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1331:11)
#6      SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1176:5)
#7      _invoke (dart:ui/hooks.dart:312:13)
#8      PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:419:5)
#9      _drawFrame (dart:ui/hooks.dart:283:31)

The error show that "view.document.documentElement" in function "WebFController.preload" is null. It seems did not create "documentElement" when exec "initDocument".
And I found that the function "readNativeUICommandMemory" in file "lib/src/bridge/to_native.dart" only return eight commands. That may be the native function "getUICommandItems" run unusually, but I do not why. The operation status is as follows：
![image](https://github.com/user-attachments/assets/7d44f618-8582-4dc4-8db7-0251df78681c)

**Comment by andycall** [comment]
Test passed on my machine, make sure your binary compiled success before you start build your flutter apps.

<img width="1422" alt="image" src="https://github.com/user-attachments/assets/0d134e56-a0d9-4ab3-be2d-30bd89397dc6" />

Or check the example app I built on your devices:

[bundle.zip](https://github.com/user-attachments/files/18291131/bundle.zip)
